#ifndef NXPNFCRDLIB_VERSION_INFO_H_INCLUDED
#define NXPNFCRDLIB_VERSION_INFO_H_INCLUDED

/*----------------------------------------------------------------------------*/
/* Copyright 2012-2020 NXP                                                    */
/*                                                                            */
/* NXP Confidential. This software is owned or controlled by NXP and may only */
/* be used strictly in accordance with the applicable license terms.          */
/* By expressly accepting such terms or by downloading, installing,           */
/* activating and/or otherwise using the software, you are agreeing that you  */
/* have read, and that you agree to comply with and are bound by, such        */
/* license terms. If you do not agree to be bound by the applicable license   */
/* terms, then you may not retain, install, activate or otherwise use the     */
/* software.                                                                  */
/*----------------------------------------------------------------------------*/
/*
 * Version Information
 * Auto-Generated by:
 *     docs\22_rel_doc\version_update.py (v2020.07.15_00)
 *
 * Do not edit this file. Update version_info.txt instead. */

#define NxpNfcRdLib_VER_FILEDESCRIPTION    "NxpNfcRdLib_06.11.00_20210409"
#define NxpNfcRdLib_VER_FILEVERSION         6,11,0,2
#define NxpNfcRdLib_VER_FILEVERSION_STR    "6,11,0,2"
#define NxpNfcRdLib_VER_PRODUCTVERSION      6,11,0,2
#define NxpNfcRdLib_VER_PRODUCTVERSION_STR "6,11,0,2"
#define NxpNfcRdLib_VER_MAJOR  (6)
#define NxpNfcRdLib_VER_MINOR  (11)
#define NxpNfcRdLib_VER_DEV    (0)

/* ______GENERATED_FROM____version_info.txt
 * # _____________________________________________________________________________
 * # Product Description
 * #
 * sw_c_define_name = "NxpNfcRdLib"
 * sw_product_name  = "NxpNfcRdLib" # Product Name
 * sw_cs_namespace  = "NxpNfcRdLibNet" # C# Namespace
 * sw_v_major       = "06"      # Major Release NNX
 * sw_v_minor       = "11"      # SW Minor Version
 * sw_v_dev         = "00"      # SW Development Version
 * sw_maturity      = "B"       # SW Maturity "A" Alpha, "B":Beta, "P": Production
 * sw_metastring    = ""        # Any meta string
 * # _____________________________________________________________________________
 * #
 * # History: Descending
 * # 06.11.00         : NxpNfcRdLib_06.11.00_20210409
 * #                  : - [artf840856] PN5190 HAL Updated to solve EMVCo Digital and Analog Compliance.
 * # 06.10.00         : NxpNfcRdLib_06.10.00_20210216
 * #                  : - [artf810005] Provided support for ECP Package.
 * #                  : - [artf816426] Updated RM Sensitivity settings during EMD Enable in PN5190 HAL for EMVCo Analog Compliance.
 * # 06.09.00         : NxpNfcRdLib_06.09.00_20201128
 * #                  : - [artf767957][artf803631] Updated PN5190 HAL ISO18000 Inventory and Resume Inventory to handle Multiple Card detection by parsing number of timeslots done by FW.
 * #                  : - [artf797180] Load Protocol updates are reverted in ApplyProtocolSettings flow for Active Target Mode of PN5190.
 * #                  : - [artf802529] Fixed complilation warnings in Linux build.
 * #                  : - [artf768416] Updated TypeB Prime example based on PN5190 FW fix w.r.t LoadRFProtocol configuration w.r.t TypeB Prime.
 * # 06.08.00         : NxpNfcRdLib_06.08.00_20201112
 * #                  : - [artf794387] Coverity issues fixed in MFDF Light and VCA components.
 * #                  : - [artf797180] Load Protocol updates in ApplyProtocolSettings flow for Active Target Mode of PN5190.
 * #                  : - [artf799201] T(VEN) is updated in PN5190 HAL to 5 milli sec as per the PN5190 data sheet.
 * #                  : - [artf799309] Updated HAL PN5190 to support performing Receive operation in Target Mode without calling Autocoll but instead LoadRfConfiguration for Target Mode
 * #                  : - [artf793689] Updated Ex-6 to configure the GPIO3 polarity for ULPCD functionality to work with PN5190 Customer Evaluation board.
 * # 06.07.00         : NxpNfcRdLib_06.07.00_20201016
 * #                  : - [artf788466] Type B Delta Frame waiting time is increased to fix DTA CR11 DP Test Failure.
 * #                  : - [artf582803] Updated forbidden MIFARE terms with correct terms in the source code.
 * #                  : - [artf784820] Field Reset Flow for Active Mode is updated to perform ApplyProtocolSettings for Active Protocol Configurations.
 * #                  : - [artf772845] Fixing Tx/Rx baudrate changes while PSL Switch for Active Target Mode.
 * # 06.06.00         : NxpNfcRdLib_06.06.00_20200924
 * #                  : - [artf692398] [artf769267] [artf692397] CMakeList update based on inclusion of new AL Components.
 * #                  : - [artf739331] Updated HAL PN5190 to wait for a configurable Timeout to receive Response TLV when Exchange TLV is sent
 * #                  :                to PN5190 Reader IC. Incase of Timeout, SWITCH_MODE_NORMAL TLV will be sent to terminate Exchange TLV CMD.
 * #                  : - [artf777009] Updated Register definition of PN5190 HAL based on FW Change.
 * # 06.05.00         : NxpNfcRdLib_06.05.00_20200915
 * #                  : - [artf778322] PN7462AU phExCcid example updated to support only CT or both CLIF and CT.
 * #                  : - [artf756519] Support for NTag 22X AL Component from NXP RdLib to NFC RdLib.
 * #                  : - [artf769267] [artf692397] Support for MIFARE DESFire EVx contactless IC AL Component from NXP RdLib to NFC RdLib.
 * #                  : - [artf758628] Update the existing MIFARE DESFire example to support new MIFARE DESFire EV2 and MIFARE DESFire EV3 Cards.
 * #                  : - [artf692398] Support for MIFARE Plus EVx contactless IC AL Component from NXP RdLib to NFC RdLib.
 * #                  : - [artf757703] New example demostrating a sample usecase with MIFARE Plus EV1 contactless IC and MIFARE Plus EV2 contactless IC Cards.
 * #                  : - [artf209269] New LPCD Example demonstrating LPCD Timing and Threshold configurations for different Reader IC's.
 * #                  : - [artf758633] Create New example by merging functinalities of Ex1, Ex2 and Ex7.
 * #                  : - [artf775679] Split Single Mode LPCD Support in PN5190.
 * #                  : - [artf775600] As CLIF is not reporting Integrity error when Request with Integrity
 * #                  :                error is received, adding CRC SW check to validate the received packet.
 * #                  : - [artf768861] Provided configuration to set HF ATT value and use the same during ULPCD
 * #                  :                Calibration and Detection Cycle.
 * # 06.04.00         : NxpNfcRdLib_06.04.00_20200715
 * #                  : - [artf768115] Updated Register definition of PN5190 HAL.
 * #                  : - [artf763098] Updating PN5190 HAL to handle Async Abort Scenarios based on PN5190 FW changes.
 * #                  : - [artf765806] PAL 14443-4mC layer updated to add new phpalI14443p4mC_Sw_DeInit API for de-initialization.
 * #                  : - [artf765252] Resolved NxpNfcRdLib coverity issues.
 * #                  : - [artf763713] Updated PH_EER_PN5190_UNHANDLED_EVT as PH_EER_PN5190_UNEXPECTED_EVT.
 * #                  : - [artf763441] New SetConfig Key (PHHAL_HW_PN5190_CONFIG_EXPECTED_EVENT) to configure the expected
 * #                  :                Event from PN5190 Reader IC.
 * #                  : - [artf737856] Return status of Pn5190 Instruction layer is mapped to PN5190 FW return values.
 * #                  : - [artf759692] New PN5190 registers CLIF_RXCTRL_STATUS_REG, INTERPOLATED_RSSI_REG and
 * #                  :                TX_NOV_CALIBRATE_AND_STORE_VAL_REG are provided to User.
 * #                  : - [artf723121] Fix to resolve CTS Capture issue for few specific CTS Configurations.
 * #                  : - [artf738706] Updated the LPCD wakeup source config macro.
 * #                  : - [artf758343] Updated PN5190 HAL to provided ISO EMD handling feature.
 * #                  : - [artf694908] Updated the TX active Initiator LoadRF Configs as per PN5190 FW update.
 * #                  : - [artf608667] Adding support for PH_COMP_AL_MFDFEV2 component in phNfcLib.
 * #                  : - [artf758273] Adding support for MIFAREPlus EV1 component in phNfcLib.
 * #                  : - [artf757911] Adding HAL PN5190 support for FeliCa EMD Handling.
 * #                  : - [artf755995] Removed deadcode in PN5190 HAL component.
 * #                  : - [artf755023] Fixed DiscLoop return status issue when Multiple TypeB cards are placed in EMVCo Mode.
 * #                  : - [artf738712] Added Analog Test Bus support in PN5190 Instruction Layer.
 * #                  : - [artf755133] Added support of ISO15693 Rx 6.6kbps baudrate in HAL PN5190.
 * # 06.03.00         : NxpNfcRdLib_06.03.00_20200512
 * #                  : - [artf751910] Updated the Default Example and Compliance Application for FRDM-K82F MCU Debug build.
 * #                  : - [artf752345] Register definition updated in Pn5190 HAL.
 * #                  : - [artf752234] Example 8 updated with NDEF Message of type URI.
 * #                  : - [artf740713] Example 5 updated to demonstrate higher baud rate support of PN5190 with NTag 5.
 * # 06.02.00         : NxpNfcRdLib_06.02.00_20200418
 * #                  : - [artf694908] Active Mode support for PN5190 Reader IC is provided in PN5190 HAL of NxpNfcRdLib.
 * #                  : - [artf716926] 1. Updated Switch Mode LPCD command as per changes in PN5190 FW.
 * #                  :                2. Updated phhalHw_Pn5190_Instr_LPCD_SetConfig and phhalHw_Pn5190_Instr_LPCD_GetConfig API signature.
 * #                  : - [artf590540] Removed phhalHw_Pn5190_WriteRegister and phhalHw_Pn5190_ReadRegister API from HAL PN5190.
 * #                  : - [artf738708] Updated Register defination file to provide registers required for Customer.
 * #                  : - [artf726014] Bug in LPC Open while applying PULL UP/DOWN configurations for LPC1769 GPIO Pins is been corrected.
 * #                  : - [artf736929] New LPCD Example for PN5190 Reader IC is been provided.
 * #                  : - [artf737113] 1. Renamed Compliance applications with more meaningful names for easier customer understanding.
 * #                  :                2. Provided PN5190 Support in all the examples of NxpNfcRdLib with few exceptions.
 * # 06.01.00         : NxpNfcRdLib_06.01.00_20191213
 * #                  : - [artf705557] PN7462AU example phExMain not able to detect Passive/Active F212/F424 target.
 * # 06.00.00         : NxpNfcRdLib_06.00.00_20191205
 * #                  : - [artf701296] Update supported FreeRTOS kernel version in NxpNfcRdlib to v10.2.0.
 * #                  : - [artf701523] Update supported KSDK version in NxpNfcRdLib to v2.6.0.
 * #                  : - [artf702409] RC663 HAL updated to use EMD Handling logic only when SPI interface is selected.
 * #                  : - [artf614832] ReaderLibrary updates for Third edition of ISO/IEC 14443-3 (2016) and Fourth edition of
 * #                  :                ISO/IEC 14443-4 (2016) specification.
 * #                  : - [artf696746] Resolved Waveshaping issue in last bit of Frame at 848Kbps observed in Pn7462au.
 * #                  : - [artf702502] Updated the Max FDT configuration based on NFC mode, to resolve S(WTX) related FDT issue observed
 * #                  :                while sending R(NACK) during NFC forum Execution.
 * #                  : - [artf700871] Added support of RC663 Plus variant CTN530.
 * # 05.23.00         : NxpNfcRdLib_05.23.00_20191127
 * #                  : - [artf590540] GetVersion API return value of FW version is corrected.
 * # 05.22.05         : NxpNfcRdLib_05.22.05_20191121
 * #                  : - [artf590540] 1.Updated the register address of CLIF_RX_EMD_0_CONFIG, GENERAL_ERROR_STATUS, TXLDO_VOUT_CURR registers.
 * #                  :                2.Added new TXLDO_VDDPA_CONFIG, PAD_CONFIG registers for HOST to configure VDDPA and PADs.
 * #                  :                3.Added new registers such as LPCD_CALIBRATE_CTRL, IQ_CHANNEL_VALS, LPCD_CALIBRATE_STATUS for
 * #                  :                  LPCD functionality.
 * #                  :                4.Removed support of Engineering PN5190 boards from NxpNfcRdLib and MCUXpresso projects.
 * #                  :                5.HAL Pn5190 Instruction layers is cleaned-up and buffered TLV handling is been removed.
 * #                  :                6.HAL Pn5190 Instruction layers updated to handle Abort scenarios and return codes.
 * #                  :                7.NFC LIB update to build without Dicscovery Loop enabled.
 * #                  :                8.HAL Pn5190 support for TARI18.88 of ISO 18000p3m3 Protocol.
 * #                  : - [artf669279] In ReaderMode reduced RxWait time when Async Baudrates are used for TypeA and RxBaudrate is 106kbps.
 * #                  : - [artf698850] PN5190 default TxWait of FeliCa and ISO 18000p3m3 is updated to 160 and 300 micro sec.
 * #                  : - [artf693334] LPCD functionality for both Calibration and Card detection is updated as per PN5190 FW Change.
 * #                  : - [artf688796] HAL Pn5190 Autocoll functionality is updated to handle both Card mode and P2P mode return values.
 * #                  : - [artf697434] HAL Pn5190 AsynAbort implementation is updated to use SWITCH MODE NORMAL command to abort
 * #                  :                execution of PN5190 FW.
 * #                  : - [artf678281] PAL 14443-4mC update to back-up the HAL TxBuffer before sending RACK.
 * #                  : - [artf681568] Anticollision issue during collision in AtqA is used for validating UID type.
 * #                  : - [artf681827] Fixed initialization of Key-B in NfcrdlibEx4_MIFAREClassic expample.
 * # 05.22.04         : NxpNfcRdLib_05.22.04_20190913
 * #                  : - [artf590540] 1.PN5190 Register definition is been updated.
 * #                  :                2.Updated Autocoll functionality based on PN5190 FW update.
 * #                  : - [artf679889] [artf677011] Updated ISO15693 Rx and Tx datarate configuration based on PN5190 FW Update.
 * #                  : - [artf681949] PN5190 HAL AsynAbort implementation based on PN5190 new FW Abort instruction.
 * #                  : - [artf681568] PAL 14443p3a updated with Anti-collision issue with CE device and 7 byte UID card.
 * #                  :
 * # 05.22.03         : NxpNfcRdLib_05.22.03_20190809
 * #                  : - [artf590540] 1.PN5190 Autocoll API implementation is been verified.
 * #                  :                2.PN5190 Transmit and Receive API validation is completed in Passive Initiator and Target Mode.
 * #                  : - [artf663200] [artf662963] Reverted PAL 15693 FWT timing as Specification as PN5190 FW Digital Delay is working.
 * #                  : - [artf678648] NFC Forum Digital Test cases related to R(NAK) transmission faster than expected are failing with Triton.
 * #                  : - [artf672843] Provided NFCIP1 Support in PN5190 HAL.
 * #                  : - [artf676912] ISO14443-4mC PAL updated during Tx chaining to resend I block when PCD send RNACK with correct/incorrect block number.
 * #                  :
 * # 05.22.02         : NxpNfcRdLib_05.22.02_20190711
 * #                  : - [artf590540] 1.Updated API Signature of phhalHw_Pn5190_Instr_RetrieveRfConfiguration.
 * #                  :                2.Changed the functionality of Receive to Retrieve RF Data.
 * #                  :                3.Updated the API Return status of HAL PN5190 Instruction Layer as per new PN5190 Instruction Document.
 * #                  :                4.Changed the HAL Wait API implementation to use PN5190 Timer 0 event instead of OSAL Time-out.
 * #                  : - [artf667558] PAL SLI15693 is FDT time-out changes are reverted as the Digital Delay Implementation of PN5190 is implemented.
 * #                  :
 * # 05.22.01         : NxpNfcRdLib_05.22.01_20190621
 * #                  : - [artf590540] 1.Write and Read EEPROM API's are provided in the Release.
 * #                  :                2.Support for ISO15693 with basic sanity testing is provided in this Release.
 * #                  :                3.CTS Event enable configuration is provided as updated in PN5190 Instruction Datasheet.
 * #                  : - [artf667558] PAL SLI15693 is updated with extra guard time to provide ISO15693 functionality.
 * #                  : - [artf667134] Updated TxWait configuration for EMVCo mode for TypeA and TypeB protocols.
 * #                  :
 * # 05.22.00         : NxpNfcRdLib_05.22.00_20190607
 * #                  : - [artf665291] NTag 42X DNA AL is part of NxpNfcRdLib Public and NDA Release.
 * #                  : - [artf596566] PN5180 HAL is updated for Sony FeliCa EMD Handling feature supported with PN5180 FW V04.01.
 * #                  : - [artf651679] BAL Exchange sequence in PN5180 HAL is updated on similar lines as per recommendation when
 * #                  :                Test Bus is enabled.
 * #                  :
 * # v5.21.00         : NxpNfcRdLib_05.21.00_20181219
 * #                  : - [artf626473] Crypto LRP code is been removed from package and the MIFARE DESFire Light AL dependency on LRP Crypto
 * #                  :                is been removed and shall only work in MIFARE DESFire EV2 mode.
 * #                  :
 * # v5.20.00         : NxpNfcRdLib_05.20.00_20181207
 * #                  : - [artf559788] NxpNfcRdLib Reader Library is been updated for below NFC Forum Technical Specification.
 * #                  :                1) NFC Forum Activity Specification v1.1.
 * #                  :                2) NFC Forum Digital Specification v1.1.
 * #                  :                3) NFC Forum LLCP Specification v1.2.
 * #                  : - [artf559793] DTA Application is been updated as per CR11 and the NXP NFC Reader Library is compliant to
 * #                  :                CR11 certification (Internal certification run).
 * #                  :                1) PN5180 and PN7462AU is compliant to Universal Device.
 * #                  :                2) RC663 is compliant to Reader Device.
 * #                  : - [artf605634] NFC CCID Example is been updated to handled CCID 'Icc Power On' and 'Icc Power Off' commands even
 * #                  :                even though automatic device activation is supported.
 * #                  : - [artf612061] Updated the return value of NFC LIB to be more meaningful.
 * #                  : - [artf626473] MIFARE DESFire Light AL is part of NxpNfcRdLib Public and NDA Release.
 * #                  : - [artf606157] ISO10373 PICC Compliance application is been updated to support latest Test suite v3.1.2 from MicroPross.
 * #                  : - [artf602908] ISO10373 PCD Compliance application is been updated to support latest Test suite v2.0.2 from MicroPross.
 * #                  :
 * # v5.19.00         : NxpNfcRdLib_05.19.00_20180810
 * #                  : - [artf559788] NxpNfcRdLib Reader PAL components are been updated as per NFC Forum Digital Specification v1.1.
 * #                  : - [artf562043] NXP NFC Reader Library is been updated as per EMVCo Digital Specification v3.0.
 * #                  : - [artf575800] Handling of higher FSD and FSC values as per EMVCo Digital Specification v3.0 in PAL 14443-4.
 * #                  : - [artf575799] PPS command can now be used in EMVCo Mode.
 * #                  :
 * # v5.18.00         : NxpNfcRdLib_05.18.00_20180723
 * #                  : - [artf593858] FWT calculation in PAL 14443-4a component exceeds EMVCo specification value.
 * #                  : - [artf594175] FWT calculation in PAL 14443-3b component exceeds EMVCo specification value.
 * #                  : - [artf582803] Don't use forbidden MIFARE terms in source code.
 * #                  : - [artf572141] Fix the test cases which are unstable in PAL Felica test suite of Reader Test Bench.
 * #                  :
 * # v5.17.00         : NxpNfcRdLib_05.17.00_20180625
 * #                  : - [artf575800] NxpNfcRdLib update to support higher FSDI and FSCI Values as per  EMVCo v3.0.
 * #                  : - [artf575799] NxpNfcRdLib update to support PPS command as per  EMVCo v3.0.
 * #                  :
 * # v5.16.00         : NxpNfcRdLib_05.16.00_20180426
 * #                  : - [artf571199] Reverted usage of GPIO2 to GPIO7 in HIF example as per v5.14 release.
 * #                  :
 * # v5.15.00         : NxpNfcRdLib_05.15.00_20180413
 * #                  : - [artf563985] TypeA asyn-baudrate issue with RC663Plus is been resolved.
 * #                  : - [artf552726] Support for new PNEV7462C board.
 * #                  :
 * # v5.14.00         : NxpNfcRdLib_05.14.00_20180305
 * #                  : - [artf387108] Resolved all the HAL RC663 recursive function calls.
 * #                  : - [artf554069] Removed dead code in PAL 18000p3m3.
 * #                  : - [artf246219] Update HAL RC663 with new Command API to support PRBS.
 * #                  : - [artf268677] Bug fix in TOP T2T Read NDEF message > 1Kbytes.
 * #                  : - [artf553042] Update in PAL 14443-4mC parsing logic to check FCS for FSCT4AT,MIN.
 * #                  :
 * # v5.13.02         : NxpNfcRdLib_05.13.02_20180226
 * #                  : - [artf555427] Update to use correct product derivative ID of CLRC661.
 * #                  :
 * # v5.13.01         : NxpNfcRdLib_05.13.01_20180215
 * #                  : - [artf555427] Support of CLRC661 Product derivative in HAL RC663 of NxpNfcRdLib.
 * #                  :
 * # v5.13.00         : NxpNfcRdLib_05.13.00_20180206
 * #                  : - [artf272959] HAL RC663 is optimized for T1T exchange operations.
 * #                  : - [artf548812] HAL PN5180 and RC663 is updated to return correct status in case of Parity/CRC error while performing T1T exchange.
 * #                  : - [artf543700] Bug fix in ActivateCard() API of PAL 14443-3A to retry Select in case of Time out.
 * #                  : - [artf544924] Bug fix in RATS API of PAL 14443-4A to parse Deselect response correctly.
 * #                  :
 * # v5.12.00         : NxpNfcRdLib_05.12.00_20171215
 * #                  : - [artf509308] Allow configuration of Q and I value of 0x00h and 0x3Fh from LPCD Calibration cycle in HAL RC663.
 * #                  : - [artf387105] Provide Guard Timer callback in HAL DataParams of PN5180.
 * #                  :
 * # v5.11.00         : NxpNfcRdLib_05.11.00_20171127
 * #                  : - [artf272425] New Compliance Example to test EMVCo 2.6b Interoperability as per bulletin No 195.
 * #                  : - [artf264271] MISRA Compliance Fixes.
 * #                  : - [artf245086] Fix in RC663 HAL to not turn ON RF Field when Apply Protocol Settings of 18000p3m3.
 * #                  : - [artf265660] HAL PN7462AU SetConfig support for Tx configuration of 1 out of 4 encoding of ISO15693.
 * #                  : - [artf233606] DAL update in LPC1769 to configured supported SPI Baud rate.
 * #                  :
 * # v5.10.00         : NxpNfcRdLib_05.10.00_20171023
 * #                  : - [artf266705] Discovery Loop is updated to support detect/activate of multiple T2T cards.
 * #                  : - [artf263903] Compliance Applications are updated to use common phApp_Init.c and phApp_Init.h files.
 * #                  : - [artf285952] PN5180 Initialization is updated to check FW version rather than reading if TestBus
 * #                  :                is enabled or not while determining if TestBus is enabled or not.
 * #                  : - [artf285846] 18000p3m3ResumeInventory logic in DUT HAL is updated to send correct RxData and length.
 * #                  : - [artf270778] PAL 18092mT Receive API is updated to call phDriver_TimerStop() API correctly based on
 * #                  :                Rx State and also PN7462AU DAL is updated handle Timer Stop when Start is not called before.
 * #                  : - [artf272037] DAL of LPC1769 and K82 is updated to provide HW Timer priority configuration as defined
 * #                  :                in the corresponding board header file.
 * #                  :
 * # v5.09.00         : NxpNfcRdLib_05.09.00_20170925
 * #                  : - [artf264271] Addressed few of the Coverity MISRA warnings.
 * #                  : - [artf264120] ICODE DNA Tag Detection and Activation Should be added in NfcrdlibEx5_ISO15693.
 * #                  : - [artf252642] Check for Software KeyStore Component use in each of the example.
 * #                  : - [artf259688] phceT4T - Writing the NDEF message ( minus 2 bytes of Length) of exact size as NDEF file fails.
 * #                  :
 * # v5.08.00         : NxpNfcRdLib_05.08.00_20170907
 * #                  : - [artf264129] Optimize RC663 HAL for WUPA and WUPB transaction time.
 * #                  :
 * # v5.07.00         : NxpNfcRdLib_05.07.00_20170824
 * #                  : - [artf264129] MISRA Compliance Fixes
 * #                  : - [artf265389] HAL PN5180 18000p3m3Inventory API is been updated to clear all interrupts.
 * #                  :
 * # v5.06.00         : NxpNfcRdLib_05.06.00_20170811
 * #                  : - [artf264129] MISRA Compliance Fixes
 * #                  :
 * # v5.05.00         : NxpNfcRdLib_05.05.00_20170804
 * #                  : - [artf260455] Optimization of Poll Guard time with Pn5180 to improve
 * #                  :   Emvco Poll guard time performance
 * #                  :
 * # v5.04.00         : NxpNfcRdLib_05.04.00_20170704
 * #                  : Fixed:
 * #                  : - [artf253094] : HAL Pn5180 reports error in case communication with FW is not reliable.
 * #                  : - [artf240116] : Optimized EMVCo transaction time for customer timing requirements.
 * #                  : - [artf247520] : Updated Readme.txt files in Examples for simplicity by pointing to UM/AN.
 * #
 * # v5.03.00         : NxpNfcRdLib_05.03.00_20170529
 * #                  : Fixed: [artf231388] [artf238247] [artf238354] [artf233747]
 * #                  : [artf229354] [artf250086].
 * #                  :
 * # v5.02.00         : NxpNfcRdLib_05.02.00_20170428
 * #                  : Fixed: [artf244581] [artf245092] [artf246209] [artf222992] [artf246524]
 * #                  : bugs identified in TOP-T5T.
 * #                  : Fixed: [artf246186] [artf247264] in Examples
 * #                  :
 * # v5.01.00         : NxpNfcRdLib_05.01.00_20170414
 * #                  : - SPI NSS Handling moved to HAL
 * #                  : - AL ISO15693 / AL-SLI / AL-ICode DNA merged into single component AL-ICode
 * #                  : - Fix Pn5180 HAL to handle PHHAL_HW_CONFIG_POLL_GUARD_TIME_US==0
 * #                  : - PR Fixes in AL-TOP-T5T
 * #                  : - Updates for Plutus integration/development
 * #                  : - 18000P3M3 updates in HAL 5180 / 7462AU
 * #                  :
 * # v5.00.00         : NxpNfcRdLib_05.00.00_DAL_20170323
 * #                  : Initial internal tag with DAL(phDriver) and phOsal
 * #                  :
 * # v4.06.00         : NxpNfcRdLib_04.06.00_20170209
 * #                  : Fixed:[artf222524] [artf222525] [artf222533] [artf222535] [artf222537]
 * #                  :       [artf222538] [artf224045] [artf221217] [artf223976] [artf221408]
 * #                  :       [artf221407] and [artf173301]
 * #                  :
 * # v4.050.03.011702 : NxpNfcRdLib_v4.050.03.011702
 * #                  : Fixes [artf220074] and [artf222751]
 * #                  :
 * # v4.050.03.001651 : NxpNfcRdLib_v4.050.03.001651
 * #                  : Feedback from internal NXP
 * #                  :
 * # v4.050.02.001650 : NxpNfcRdLib_v4.050.02.001650
 * #                  : Fixed: [artf218286] [artf218337] [artf203532] [artf217665] [artf219615]
 * #                  :        [artf203969] [artf219481] [artf217069]
 * #                  : Open:  [artf219908] [artf219913]
 * #                  :
 * #                  :
 * # v4.050.01.001650 : NxpNfcRdLib_v4.050.01.001650_20161214
 * #                  : Release from GIT
 * #				   : [artf218286] [artf218337] [artf203532] [artf217665]
 * #                  :
 * # v4.050.00.001649 : NxpNfcRdLib_v4.050.00.001649_20161205
 * #                  : Release from GIT
 * #                  :
 * # v4.040.05.011646 > NxpNfcRdLib_v4.040.05.011646_20161115
 * #                  > [artf212345] : Linux Porting updates for phOsal_ThreadDelay
 * #                  > [artf212238] : Enable On-Board Pull Up by SW for IRQ pin used for RC523.
 * #                  >
 * # v4.040.05.001642 > NxpNfcRdLib_v4.040.05.001642_20161017
 * #                  > Fixed [artf200311] #FRDM
 * # v4.040.04.001641 > NxpNfcRdLib_v4.040.04.001641_20161010
 * #                  > Fixed for artifacts : [artf205559] [artf205886] [artf205966]
 * #                  :
 * # v4.040.03.001640 : NxpNfcRdLib_v4.040.03.001640_20161005
 * #                  : Linux support
 * # V4.040.02.001638 : NxpNfcRdLib_v4.040.02.001638_20160923
 * #				   : Release of Simplified API - EMVCo profile and beta code of ISO Profile.
 * #				   : Fixed for artifacts : artf193863 artf191954 artf199412
 * # v4.040.01.001637 : NxpNfcRdLib_v4.040.01.001637_20160916
 * # v4.040.00.001636 : NxpNfcRdLib_v4.040.00.001636_20160907
 * # v4.031.00.001631 : NxpNfcRdLib_v4.031.00.001631_SmplAPI_20160801
 * # v4.030.00.011627 : PN7462AU_04.03.01_20160706 / NxpNfcRdLib_v4.030.00.011627_20160706
 * # 04.010.01.02     : Based on NFCRDLIB_V4.010.01.021604
 * # 04.010.01.02     : Based on NFCRDLIB_V4.010.01.021604
 * # 04.010.05.00     : Based on NFCRDLIB_V4.010.01.011604
 * # 04.010.04.00     : Based on NFCRDLIB_V4.010.01.001603
 * # 04.010.03.00     : Based on NxpRdLib_4.010.00.001601_ExC
 * #                  : Based on @r4100 - 2016.01.07 of
 * #                  :    /branch/NxpNfcRdLib_Branch_R_Gate_V4.010.00.001601
 * #                  :
 * # 04.010.02.00     : Based on NxpRdLib_4.010.00.001551_ExC
 * # 04.010.01.00     : Based on NfcRdLib_V_Gate_RC3_V4.010.01.001550
 * # 03.092.11.04     : Based on NfcRdLib_V_Gate_PN5180_V3.092.12.001547
 * #                  : +Fix for artf126517 Frame Delay Time Listen -> Poll is not
 * #                  : being changed based on the minimum TR2 value received in sensb
 * #                  : res
 * # 03.092.11.03     : PN7462AU_02_07_00_MRA2_20151113
 * # 03.092.11.00     : Based on NfcRdLib_V_Gate_RC3_V3.092.11.001546
 * # 03.092.11.00     : Based on branch/NfcRdLib_V_Gate_RC2_V3.092.11.001541 (V3.092.11.001545)
 * # 03.092.11.00     : Based on NfcRdLib_V_Gate_RC2_V3.092.11.001541_TempWk45
 * # 03.092.10.00     : Based on V3.092.10.001539 of NxpRdLib
 * # 03.092.07.01     : Corresponding to PN7462AU_02_06_00_MRA2_20150911 Drop
 * # 03.092.07.00     : Based on V3.092.07.001537 of NxpRdLib
 * # 03.092.05.00     : Based on v3.092.05.001534 of NxpRdLib
 * # 03.090.00.00     : Based on v3.092.00.001529 of NxpRdLib
 * # 03.080.06.00     : Based on v3.082.06.001528 of NxpRdLib
 * # 03.080.05.00     : Based on v3.082.05.001526 of NxpRdLib
 * # 03.080.04.00     : Based on v3.082.04.001524 of NxpRdLib
 * # 03.080.03.01     : Fixes for artifacts : artf631092, artf631750, artf631751
 * # 03.080.03.00     : Based on v3.082.03.001522 of NxpRdLib
 * # 03.080.01.00     : Based on V3.082.01.001518 of NxpRdLib
 * # 03.080.00.00     : Based on V3.082.00.001516 of NxpRdLib
 * # 03.010.04.00     : Release PN640FLASH_00_08_00_20150227 with NxpRdLib
 * # 03.010.03.00     : Updated with the fix of DUT Handling Mode and
 * #                    HIF Frame mode for compatibility between LPC and DUT.
 * # 03.010.02.02     : UHost::DUT_Switch Renamed to UHost_HIF_Switch
 * # 03.010.02.01     : HIF Related changes
 * # 03.010.02.00     : Corresponding to pn640Flash_00.03.00_DEV_20140905
 * # 03.010.01.02     : phhalHw_UHost_GetVersion returns 32bit Dev Value
 * # 03.010.01.01     : Corresponding to pn640Flash_00.02.01_CES_TST_20140904
 * # 03.010.01.00     : Corresponding to pn640Flash_00.02.00_Dev_20140808
 * # 03.010.00.00     : Migrated to UHost/DUT based NxpRdLib
 * # 03.000.01.00     : Initial Release
 * # _____________________________________________________________________________
 */

#endif /* NXPNFCRDLIB_VERSION_INFO_H_INCLUDED */
